#!/bin/sh
echo "VVP valgrind errors."
echo "-------------------------"
fgrep "ERROR SUMMARY" log/*.log | fgrep -v " 0 errors" || echo "No Errors."

fgrep -H "definitely lost" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"definitely lost\" memory in vvp."

fgrep -H "indirectly lost" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"indirectly lost\" memory in vvp."

fgrep -H "possibly lost" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"possibly lost\" memory in vvp."

fgrep -H "still reachable" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"still reachable\" memory in vvp."

# egrep "^\*\*[0-9]+\*\*" log/*.log || echo "No \"missed deletes\" in vvp."

echo ""
echo "VPI valgrind errors."
echo "-------------------------"
fgrep "ERROR SUMMARY" vpi_log/*.log | fgrep -v " 0 errors" || echo "No Errors."

fgrep -H "definitely lost" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"definitely lost\" memory in vvp."

fgrep -H "indirectly lost" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"indirectly lost\" memory in vvp."

fgrep -H "possibly lost" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"possibly lost\" memory in vvp."

fgrep -H "still reachable" log/*.log | fgrep -v " 0 bytes" || \
  echo "No \"still reachable\" memory in vvp."

# egrep "^\*\*[0-9]+\*\*" vpi_log/*.log || echo "No \"missed deletes\" in vvp."
